class Page(object):
    def __init__(self, chinese, answer, hint='', error_count_before_hint=2, show_survey=0,
                 is_test=False, marker_data = ''):
        self.chinese = chinese
        self.answer = answer
        self.error_count_before_hint = error_count_before_hint
        self.hint = hint
        self.show_survey = show_survey
        self.is_test = is_test
        self.marker_data = marker_data

PAGES = [
    Page('红', 'red', hint='红 = red'),
    Page('黄', 'yellow', hint='黄 = yellow'),
    Page('红', 'red'),
    Page('黄', 'yellow'),
    Page('红', 'red'),
    Page('黄', 'yellow'),
    Page('红', 'red'),
    Page('黄', 'yellow'),
    Page('红', 'red'),
    Page('黄', 'yellow', show_survey=1),
    
    Page('绿', 'green', hint='绿 = green'),
    Page('绿', 'green'),
    Page('紫', 'purple', hint='紫 = purple'),
    Page('紫', 'purple'),
    Page('绿 紫', 'green purple'),
    Page('紫 绿', 'purple green'),
    Page('蓝', 'blue', hint='蓝 = blue'),
    Page('蓝', 'blue'),
    Page('蓝 绿', 'blue green'),
    Page('紫 蓝', 'purple blue', show_survey=2),

    Page('黑', 'black', hint='黑 = black'),
    Page('橙', 'orange', hint='橙 = orange'),
    Page('棕', 'brown', hint='棕 = brown'),
    Page('粉', 'pink', hint='粉 = pink'),
    Page('白', 'white', hint='白 = white'),
    Page('白 棕 粉', 'white brown pink'),
    Page('橙 绿 蓝', 'orange green blue'),
    Page('黑 红 粉', 'black red pink'),
    Page('紫 棕 蓝', 'purple brown blue'),
    Page('绿 黄 白', 'green yellow white', show_survey=3),

    Page('食','Food'),
    Page('稻','Rice'),
    Page('水','Water'),
    Page('汤','Soup'),
    Page('蛋','Eggs'),
    Page('奶','Milk'),
    Page('菠','Spinach'),
    Page('茶','Tea'),
    Page('饺','Dumpling'),
    Page('渴','Thirsty', show_survey=4),

    Page('狗','Dog'),
    Page('猫','Cat'),
    Page('马','Horse'),
    Page('鸭','Duck'),
    Page('龟','Turtle'),
    Page('猪','Pig'),
    Page('牛','Cow'),
    Page('虎','Tiger'),
    Page('狮','Lion'),
    Page('象','Elephant', show_survey=5),

    Page('太阳','Sun'),
    Page('月亮','Moon'),
    Page('海','Sea'),
    Page('山','Mountain'),
    Page('河','River'),
    Page('树','Tree'),
    Page('风','Wind'),
    Page('云','Cloud'),
    Page('雨','Rain'),
    Page('丛林','Jungle', show_survey=6),

    Page('家','Home'),
    Page('文库','Library'),
    Page('火车站','Train Station'),
    Page('美国','America'),
    Page('餐厅','Restaurant'),
    Page('市场','Market'),
    Page('学校','School'),
    Page('剧院','Theatre'),
    Page('操场','Playground'),
    Page('法庭','Courtroom', show_survey=7),

    Page('表','Table'),
    Page('椅子','Chair'),
    Page('框','Box'),
    Page('灯','Lamp'),
    Page('书','Book'),
    Page('碗','Bowl'),
    Page('纸','Paper'),
    Page('车','Car'),
    Page('袋','Bag'),
    Page('销','Pin', show_survey=8),

    #German Section

    Page('Suppe','Soup'),
    Page('Saft','Juice'),
    Page('Ei','Egg'),
    Page('ApfelSaft','Apple Juice'),
    Page('Käse','Cheese'),
    Page('Salz','Salt'),
    Page('Knödel','Dumpling'),
    Page('Milk','Milch'),
    Page('Wasser','Water'),
    Page('Reis','Rice', show_survey=9),

    Page('Baum','Tree'),
    Page('Meer','Sea'),
    Page('Luft','Air'),
    Page('Berg','Mountain'),
    Page('Regen','Rain'),
    Page('Blume','Flower'),
    Page('Sonne','Sun'),
    Page('Mond','Moon'),
    Page('Fluss','River'),
    Page('Wolke','Cloud',show_survey=10),

    Page('Hemd','Shirt'),
    Page('Hose','Pants'),
    Page('Kleider','Clothes'),
    Page('Rock','Skirt'),
    Page('Socks','Socken'),
    Page('Shoes','Schuhe'),
    Page('Button','Knopf'),
    Page('Jacket','Mantel'),
    Page('Jacket','Jacke'),
    Page('Hats','Hüte',show_survey=11),


    Page('Kuh','Cow'),
    Page('Pferd','Horse'),
    Page('Ente','Duck'),
    Page('Hund','Dog'),
    Page('Katze','Cat'),
    Page('Bär','Bear'),
    Page('Vogel','Bird'),
    Page('Maus','Mouse'),
    Page('Fliege','Fly'),
    Page('Löwe','Lion',show_survey=12),

    Page('Zeug','Stuff'),
    Page('Feuerzeug','Lighter'),
    Page('Spielzeug','Toy'),
    Page('Werkzeug','Tool'),
    Page('Fahrzeug','Vehicle'),
    Page('Flugzeug','Airplane'),
    Page('Stuhl','Chair'),
    Page('Maus','Mouse'),
    Page('Buch','Book'),
    Page('Stift','Pen',show_survey=13),

    Page('Bibliothek','Library'),
    Page('Bahnhöfe','Train Station'),
    Page('Gebäude','Building'),
    Page('Garten','Garden'),
    Page('Zimmer','Room'),
    Page('Stadt','City'),
    Page('Brücke','Bridge'),
    Page('Dorf','Village'),
    Page('Markt','Market'),
    Page('Straße','Street',show_survey=14)
]

print(len(PAGES))

